//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string bTitle { get; set; }
        public string bAuthor { get; set; }
        public string bISBN { get; set; }
        public Nullable<int> PublishedYear { get; set; }
        public int AvailableCopies { get; set; }
        public Nullable<int> BorrowedBy { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
